name: test_env_xgcm
channels:
  # Get the latest numba from numba/label/dev
  - numba/label/dev
  - conda-forge
dependencies:
  - codecov
  - docrep<=0.2.7
  - numba
  - numpy
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - python
  - toolz
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/dask/dask.git
    - git+https://github.com/dask/distributed.git
